# Generated by Django 6.0.2 on 2026-02-25 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchased_prints', models.ManyToManyField(blank=True, related_name='purchased_by', to='gallery.artprint', verbose_name='Purchased Prints')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ManyToManyField(blank=True, help_text='Art prints the user has favourited for later.', related_name='wishlisted_by', to='gallery.artprint', verbose_name='Wishlist')),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
