# Generated by Django 6.0.2 on 2026-02-25 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArtPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='prints/%Y/%m/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('size_options', models.CharField(blank=True, help_text='e.g. A4, A3, 50x70cm – comma separated', max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('limited_edition', models.PositiveIntegerField(blank=True, help_text='Number remaining or leave blank if unlimited', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prints', to='gallery.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
