# Generated by Django 6.0.2 on 2026-02-25 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short name for your commission', max_length=200)),
                ('commission_type', models.CharField(choices=[('icon', 'Icon'), ('logo', 'Logo'), ('poster', 'Poster'), ('portrait', 'Character Portrait'), ('other', 'Other')], max_length=100)),
                ('size', models.CharField(help_text='e.g. 1080x1080px, A3 print, custom', max_length=100)),
                ('description', models.TextField()),
                ('reference_images', models.ImageField(blank=True, null=True, upload_to='commissions/references/%Y/%m/')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('quoted', 'Quoted – Awaiting Deposit'), ('in_progress', 'In Progress'), ('revision', 'Revision Requested'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('artist_notes', models.TextField(blank=True, help_text='Internal notes – visible only to admin')),
                ('final_file', models.FileField(blank=True, null=True, upload_to='commissions/final/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
